import {format, formatDistanceToNowStrict} from "date-fns";

export const globalAppointmentColumns = [
  {
    name: "S/N",
    key: "sn",
    description: "SN",
    selector: row => row.sn,
    sortable: true,
    inputType: "HIDDEN",
    width: "60px",
  },
  {
    name: "Date/Time",
    key: "date",
    description: "Date/Time",
    selector: row =>
      row.start_time
        ? format(new Date(row.start_time), "dd/MM/yyyy HH:mm")
        : "",
    sortable: true,
    required: true,
    inputType: "TEXT",
  },
  {
    name: "First Name",
    key: "firstname",
    description: "First Name",
    selector: row => row.firstname,
    sortable: true,
    required: true,
    inputType: "TEXT",
  },

  {
    name: "Last Name",
    key: "lastname",
    description: "Last Name",
    selector: row => row.lastname,
    sortable: true,
    required: true,
    inputType: "TEXT",
  },
  {
    name: "Classification",
    key: "classification",
    description: "Classification",
    selector: row => row.appointmentClass,
    sortable: true,
    required: true,
    inputType: "TEXT",
  },
  {
    name: "Location",
    key: "location",
    description: "Location",
    selector: row => row.location_name,
    sortable: true,
    required: true,
    inputType: "TEXT",
  },
  {
    name: "Type",
    key: "type",
    description: "Type",
    selector: row => row.appointment_type,
    sortable: true,
    required: true,
    inputType: "TEXT",
  },
  {
    name: "Status",
    key: "status",
    description: "Status",
    selector: row => row.appointment_status,
    sortable: true,
    required: true,
    inputType: "TEXT",
  },
  {
    name: "Reason",
    key: "reason",
    description: "Reason",
    selector: row => row.appointment_reason,
    sortable: true,
    required: true,
    inputType: "TEXT",
  },
  {
    name: "Practitioner",
    key: "practitioner",
    description: "Practitioner",
    selector: row => row.practitioner_name,
    sortable: true,
    required: true,
    inputType: "TEXT",
  },
  // New check-in/check-out and encounter timestamps (global)
  {
    name: "Checked in",
    key: "checkedin_at",
    description: "Checked in at",
    selector: row => (row.checkedin_at ? format(new Date(row.checkedin_at), "dd/MM/yyyy HH:mm") : ""),
    sortable: true,
    inputType: "DATETIME",
  },
  {
    name: "Checked out",
    key: "checkedout_at",
    description: "Checked out at",
    selector: row => (row.checkedout_at ? format(new Date(row.checkedout_at), "dd/MM/yyyy HH:mm") : ""),
    sortable: true,
    inputType: "DATETIME",
  },
  {
    name: "Encounter start",
    key: "encounter_started_at",
    description: "Encounter started at",
    selector: row => (row.encounter_started_at ? format(new Date(row.encounter_started_at), "dd/MM/yyyy HH:mm") : ""),
    sortable: true,
    inputType: "DATETIME",
  },
  {
    name: "Encounter end",
    key: "encounter_ended_at",
    description: "Encounter ended at",
    selector: row => (row.encounter_ended_at ? format(new Date(row.encounter_ended_at), "dd/MM/yyyy HH:mm") : ""),
    sortable: true,
    inputType: "DATETIME",
  },
  {
    name: "Module",
    key: "practitioner",
    description: "Practitioner",
    selector: row => row.location_type,
    sortable: true,
    required: true,
    inputType: "TEXT",
  },
];

export const AppointmentSchema = [
  {
    name: "S/N",
    key: "sn",
    description: "SN",
    selector: row => row.sn,
    sortable: true,
    inputType: "HIDDEN",
    width: "60px",
  },
  {
    name: "Date/Time",
    key: "date",
    description: "Date/Time",
    selector: row =>
      row.start_time
        ? format(new Date(row.start_time.slice(0, 19)), "dd/MM/yyyy HH:mm")
        : "",
    sortable: true,
    required: true,
    inputType: "TEXT",
    width: "100px",
  },
  {
    name: "First Name",
    key: "firstname",
    description: "First Name",
    selector: row => row.firstname,
    sortable: true,
    required: true,
    inputType: "TEXT",
    width: "100px",
  },

  {
    name: "Last Name",
    key: "lastname",
    description: "Last Name",
    selector: row => row.lastname,
    sortable: true,
    required: true,
    inputType: "TEXT",
    width: "100px",
  },
  {
    name: "Classification",
    key: "classification",
    description: "Classification",
    selector: row => row.appointmentClass,
    sortable: true,
    required: true,
    inputType: "TEXT",
    width: "100px",
  },
  {
    name: "Location",
    key: "location",
    description: "Location",
    selector: row => row.location_name,
    sortable: true,
    required: true,
    inputType: "TEXT",
    width: "100px",
  },
  {
    name: "Type",
    key: "type",
    description: "Type",
    selector: row => row.appointment_type,
    sortable: true,
    required: true,
    inputType: "TEXT",
    width: "100px",
  },
  {
    name: "Status",
    key: "status",
    description: "Status",
    selector: row => row.appointment_status,
    sortable: true,
    required: true,
    inputType: "TEXT",
    width: "100px",
  },
  {
    name: "Reason",
    key: "reason",
    description: "Reason",
    selector: row => row.appointment_reason,
    sortable: true,
    required: true,
    inputType: "TEXT",
    width: "100px",
  },
  {
    name: "Practitioner",
    key: "practitioner",
    description: "Practitioner",
    selector: row => row.practitioner_name,
    sortable: true,
    required: true,
    inputType: "TEXT",
    width: "100px",
  },
  // New check-in/check-out and encounter timestamps
  {
    name: "Checked in",
    key: "checkedin_at",
    description: "Checked in at",
    selector: row => (row.checkedin_at ? format(new Date(row.checkedin_at), "dd/MM/yyyy HH:mm") : ""),
    sortable: true,
    inputType: "DATETIME",
    width: "140px",
  },
  {
    name: "Checked out",
    key: "checkedout_at",
    description: "Checked out at",
    selector: row => (row.checkedout_at ? format(new Date(row.checkedout_at), "dd/MM/yyyy HH:mm") : ""),
    sortable: true,
    inputType: "DATETIME",
    width: "140px",
  },
  {
    name: "Encounter start",
    key: "encounter_started_at",
    description: "Encounter started at",
    selector: row => (row.encounter_started_at ? format(new Date(row.encounter_started_at), "dd/MM/yyyy HH:mm") : ""),
    sortable: true,
    inputType: "DATETIME",
    width: "140px",
  },
  {
    name: "Encounter end",
    key: "encounter_ended_at",
    description: "Encounter ended at",
    selector: row => (row.encounter_ended_at ? format(new Date(row.encounter_ended_at), "dd/MM/yyyy HH:mm") : ""),
    sortable: true,
    inputType: "DATETIME",
    width: "140px",
  },
];

// TODO: Add a new  schema for Checkin
