import React, { useState, useEffect, useContext } from 'react';
import CustomTable from '../../../../components/customtable';
import { PageWrapper } from '../../../app/styles';
import { TableMenu } from '../../../../ui/styled/global';
import dayjs from 'dayjs';
import { IconButton, Typography } from '@mui/material';
import FilterMenu from '../../../../components/utilities/FilterMenu';
import ModalBox from '../../../../components/modal';
import CRMAnalyticsModal from './CRMAnalyticsModal';
import GlobalCustomButton from '../../../../components/buttons/CustomButton';
import AddCircleOutline from '@mui/icons-material/AddCircleOutline';
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline';
import CRMAnalyticsReport from './CRMAnalyticsReport';
import AssessmentOutlinedIcon from '@mui/icons-material/AssessmentOutlined';

import client from '../../../../feathers';
import { ObjectContext, UserContext } from '../../../../context';
import { useCallback } from 'react';

export default function CRMAnalyticsList({onClick}) {
  const [page, setPage] = useState(1);
  const [limit, setLimit] = useState(10);
  const [total, setTotal] = useState(0);
  const [createModal, setCreateModal] = useState(false);
  const [currentView, setCurrentView] = useState('list');
  const [facilities, setFacilities] = useState([]);
  const [loading, setLoading] = useState(false);
  const { user } = useContext(UserContext);
  const { setState } = useContext(ObjectContext);
  const reportServer = client.service('reports');

  const handleSearch = () => {};

  const handleCreateModal = () => {
    setCreateModal(true);
  };

  const handleRow = (res) => {
    setCurrentView('report');
    setState((prev) => ({ ...prev, CRMAnalyticsModule: { reportData: res } }));
  };

  const handleCreateNew = () => {
    handleCreateModal();
  };

  const handleHideCreateModal = () => {
    setCreateModal(false);
  };

  const handleGenerateReport = () => {
    setCurrentView('report');
    setCreateModal(false);
  };

  const getAnalytics = useCallback(async () => {
    try {
      setLoading(true);
      const facId = user.currentEmployee.facilityDetail._id;
      let query = {
        facilityId: facId,
        type: 'CRM Analytics',
        module: 'CRM',
        $sort: {
          createdAt: -1,
        },
        $limit: limit,
        $skip: (page - 1) * limit,
      };
      const res = await reportServer.find({ query });
      setState((prev) => ({ ...prev, CRMAnalyticsModule: { reportData: res } }) );
      setFacilities(res.data);
      setTotal(res.total);
    } catch (error) {
      console.error('Error fetching analytics:', error);
    } finally {
      setLoading(false);
    }
  }, [limit, page]);
  // console.log(facilities, 'Facilities');

  useEffect(() => {
    getAnalytics();

    const handleServerEvent = () => getAnalytics();

    reportServer.on('created', handleServerEvent);
    reportServer.on('updated', handleServerEvent);
    reportServer.on('patched', handleServerEvent);
    reportServer.on('removed', handleServerEvent);

    return () => {
      reportServer.off('created', handleServerEvent);
      reportServer.off('updated', handleServerEvent);
      reportServer.off('patched', handleServerEvent);
      reportServer.off('removed', handleServerEvent);
    };
  }, [getAnalytics]);

  const CRMAnalyticsSchema = [
    {
      name: 'S/N',
      key: 'sn',
      description: 'SN',
      selector: (row, i) => i + 1,
      sortable: true,
      inputType: 'HIDDEN',
      width: '50px',
    },
    {
      name: 'Report Name',
      key: 'name',
      description: 'Report Name',
      selector: (row) => (
        <Typography
          sx={{ fontSize: '0.8rem', whiteSpace: 'normal' }}
          data-tag="allowRowEvents"
        >
          {row?.name}
        </Typography>
      ),
      sortable: true,
      required: true,
      inputType: 'HIDDEN',
      style: {
        color: '#1976d2',
        textTransform: 'capitalize',
      },
    },
    {
      name: 'Type',
      key: 'type',
      description: 'Report Type',
      selector: (row) => row?.type,
      sortable: true,
      required: true,
      inputType: 'TEXT',
      style: {
        textTransform: 'capitalize',
      },
    },
    {
      name: 'Facility',
      key: 'facilityname',
      description: 'Facility Name',
      selector: (row) => row?.facilityname,
      sortable: true,
      required: true,
      inputType: 'HIDDEN',
    },
    {
      name: 'Period',
      key: 'period',
      description: 'Report Period',
      selector: (row) =>
        `${dayjs(row?.startdate).format('DD/MM/YYYY')} - ${dayjs(row?.enddate).format('DD/MM/YYYY')}`,
      sortable: true,
      required: true,
      inputType: 'TEXT',
      width: '200px',
    },
    {
      name: 'Generated By',
      key: 'createdbyName',
      description: 'Generated By',
      selector: (row) => row?.createdbyName || 'ADMIN MAGNIE',
      sortable: true,
      required: true,
      inputType: 'HIDDEN',
    },
    {
      name: 'Date',
      key: 'date',
      description: 'Date Generated',
      selector: (row) => dayjs(row?.createdAt).format('DD/MM/YYYY'),
      sortable: true,
      required: true,
      inputType: 'DATE',
    },
    {
      name: 'Actions',
      key: 'action',
      description: 'Actions',
      selector: (row) => (
        <IconButton size="small">
          <DeleteOutlineIcon fontSize="small" sx={{ color: 'red' }} />
        </IconButton>
      ),
      sortable: true,
      required: true,
      inputType: 'TEXT',
      width: '100px',
      center: true,
    },
  ];

  const handleGoBack = () => {
    setCurrentView('list');
  };

  const onTableChangeRowsPerPage = (size) => {
    setLimit(size);
    setPage(1);
  };

  const onTablePageChange = (newPage) => {
    setPage(newPage);
  };

  return (
    <>
      {currentView === 'list' && (
        <PageWrapper
          style={{ flexDirection: 'column', padding: '0.6rem 1rem' }}
        >

          <div style={{ marginInline: '5px', display: 'flex', gap: '1rem', justifyContent:'flex-end' }}>
          <GlobalCustomButton color="warning" onClick={onClick}>
            <AssessmentOutlinedIcon fontSize="small" sx={{ marginRight: '5px' }} />
            Show Dashboard
          </GlobalCustomButton>
        </div>

          <TableMenu>
            <div style={{ display: 'flex', alignItems: 'center' }}>
              {handleSearch && (
                <div className="inner-table">
                  <FilterMenu onSearch={handleSearch} />
                </div>
              )}
              <h2 style={{ margin: '0 10px', fontSize: '0.95rem' }}>
                CRM Analytics
              </h2>
            </div>
            <GlobalCustomButton onClick={handleCreateNew}>
              <AddCircleOutline fontSize="small" sx={{ marginRight: '5px' }} />
              Generate Report
            </GlobalCustomButton>
          </TableMenu>

          <div>
            <CustomTable
              title={''}
              columns={CRMAnalyticsSchema}
              data={facilities}
              pointerOnHover
              highlightOnHover
              striped
              onChangeRowsPerPage={onTableChangeRowsPerPage}
              onChangePage={onTablePageChange}
              onRowClicked={handleRow}
              progressPending={loading}
              pagination
              paginationServer
              paginationTotalRows={total}
            />
          </div>
        </PageWrapper>
      )}
      <ModalBox
        width="50%"
        open={createModal}
        onClose={handleHideCreateModal}
        header="CRM Report Template"
      >
        <CRMAnalyticsModal onNavigate={handleGenerateReport} />
      </ModalBox>
      {currentView === 'report' && (
        <CRMAnalyticsReport handleGoBack={handleGoBack} />
      )}
    </>
  );
}
