/**
 * CSRF Protection Utilities
 *
 * This module provides CSRF (Cross-Site Request Forgery) protection for the application.
 * CSRF tokens should be generated by the backend and validated on state-changing requests.
 *
 * Note: Full CSRF protection requires backend implementation to:
 * 1. Generate CSRF tokens on login/session creation
 * 2. Validate tokens on POST/PUT/PATCH/DELETE requests
 * 3. Set SameSite cookie flags
 */

const CSRF_TOKEN_KEY = 'csrf-token';
const CSRF_HEADER_NAME = 'X-CSRF-Token';

/**
 * Store CSRF token (typically received from backend after login)
 * @param {string} token - CSRF token from backend
 */
export const setCsrfToken = (token) => {
  if (!token) {
    console.warn('Attempted to store empty CSRF token');
    return;
  }
  sessionStorage.setItem(CSRF_TOKEN_KEY, token);
};

/**
 * Get CSRF token for request headers
 * @returns {string|null} CSRF token or null
 */
export const getCsrfToken = () => {
  return sessionStorage.getItem(CSRF_TOKEN_KEY);
};

/**
 * Remove CSRF token (on logout)
 */
export const clearCsrfToken = () => {
  sessionStorage.removeItem(CSRF_TOKEN_KEY);
};

/**
 * Get headers object with CSRF token
 * @param {Object} additionalHeaders - Any additional headers to include
 * @returns {Object} Headers object with CSRF token
 */
export const getCsrfHeaders = (additionalHeaders = {}) => {
  const csrfToken = getCsrfToken();

  if (!csrfToken) {
    console.warn('No CSRF token available for request');
    return additionalHeaders;
  }

  return {
    ...additionalHeaders,
    [CSRF_HEADER_NAME]: csrfToken,
  };
};

/**
 * Validate CSRF token format (basic client-side check)
 * @param {string} token - Token to validate
 * @returns {boolean} True if token format is valid
 */
export const isValidCsrfToken = (token) => {
  if (!token || typeof token !== 'string') return false;
  // Token should be at least 32 characters (example validation)
  return token.length >= 32;
};

/**
 * Generate a random token (for development/testing only)
 * PRODUCTION: Tokens should ALWAYS come from the backend
 * @returns {string} Random token
 */
export const generateDevCsrfToken = () => {
  console.warn('Using client-generated CSRF token - FOR DEVELOPMENT ONLY');
  return Array.from(crypto.getRandomValues(new Uint8Array(32)))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
};

export default {
  setCsrfToken,
  getCsrfToken,
  clearCsrfToken,
  getCsrfHeaders,
  isValidCsrfToken,
  generateDevCsrfToken,
};
